spring:
  # 데이터 베이스 연결 성정
  datasource:
    url: jdbc:mysql://calendar-database-1.cpntmn5epfhq.ap-northeast-2.rds.amazonaws.com/calendar?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  # OAuth2 클라이언트 설정
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${OAUTH2_GOOGLE_ID}
            clientSecret: ${OAUTH2_GOOGLE_SECRET}
            redirect-uri: https://calendars2.duckdns.org/login/oauth2/code/google
            #  http://localhost:8080/login/oauth2/code/google-> 로컬로 로그인 할 때
            scope:
              - email
              - profile
        provider:
          google:
            # access_type를 offline으로 설정해야 refreshToken이 발급 됨
            # refresh 토큰을 처음 로그인에만 발급해주기에 consent로 설정해서 상시 발급받도록 한다
            authorizationUri: https://accounts.google.com/o/oauth2/auth?access_type=offline&prompt=consent
  # 레디스 설정
  redis:
    host: ${REDIS_IP_ADDRESS}
    port: 6379
    password: ${REDIS_PASSWORD}

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 28800
  refresh-token-expiration-minutes: 420